version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  your_app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: your-app-container
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
