name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    
jobs:
  build:
    runs-on: self-hosted
      
    steps:
    - name: Stop and remove all running containers
      run: sudo docker stop $(sudo docker ps -a -q) || true && sudo docker rm $(sudo docker ps -a -q) || true

    - name: Remove all Docker images
      run: sudo docker rmi $(sudo docker images -q) || true

    - name: Docker pull images
      run: sudo docker pull dimon21221/cicd-pipeline

    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container dimon21221/cicd-pipeline
